modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Melonslise/Subterranean-Wilderness/issues" 
license="Attribution-NonCommercial 3.0 Unported"

[[mods]]
modId="subwild"
version="1.1"
displayName="Subterranean Wilderness"
displayURL="https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness"
logoFile="subwild.png"
credits="On MMD: TelepathicGrunt, Gigaherz. Special thanks to Paint_Ninja!"
authors="Melonslise"
description='''
A spiritual successor to WTF's CaveBiomes, completely rewritten and enchanced, Subterranean Wilderness aims to spice up the old vanilla caves you got bored of years ago and bring you the cave update you always wanted.

Delve deep into the depths of the earth and unfold the beauty of its wild and untouched, diverse environments and climates. Throughout your journey, you will come across the frigid, pure and flawless exteriors of glacial caves; trudge through the impassable, ravishing flora of humid tropical caves; unearth the fascinating fungal kingdoms beneath mushroom islands; discover the many stunning vibrant corals flourishing in flooded sea caves, with many, many more still waiting to be explored..
'''